using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class Order
{
    public int positionId { get; set; }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; } // Autogenerated ID

    [Required]
    public required string Ticker { get; set; }

    [Required]
    public required OrderType Type { get; set; } // Buy or Sell

    [Required]
    public required double Price { get; set; }
    public double TargetPrice { get; set; }
    public required double StopLoss { get; set; }

    [Required]
    public bool IsExitOrder { get; set; }
    public required int Quantity { get; set; } 

    public string? Notes { get; set; }
}

public enum OrderType { Buy, Sell, Modify } 