using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class Order
{
    public int positionId { get; set; }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; } // Autogenerated ID
    public required string Ticker { get; set; }
    public required OrderType Type { get; set; } // Buy or Sell
    public required double Price { get; set; }
    public double StopLoss { get; set; }
    public bool IsExitOrder { get; set; }
    public required int Quantity { get; set; } // Quantity of stocks to buy or sell
}

public enum OrderType { Buy, Sell, Modify } // Modify is used to update stop loss